CREATE TABLE score (id int(11) NOT NULL, score int(11) NOT NULL, nom varchar(128) NOT NULL);

ALTER TABLE score ADD PRIMARY KEY (id);
ALTER TABLE score MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;